baseurl = "http://nassor.me/"
languageCode = "en-us"
title = "Nassor Paulino da Silva"
description = "Software Engineering log"

[params]
  gaCode = "UA-67778437-1"

[[menu.main]]
    name = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
